[package]
name = "parts_manager"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"
description = "A GPT Partition Manager"

[dependencies]
parts = { path = "../_NiteLinux/Userspace/parts" }
structopt = "0.3.9"
anyhow = "1.0.26"
linapi = "0.4.2"
byte-unit = "3.0.3"

[dependencies.cursive]
version = "0.14.0"
default-features = false
features = [
    # "crossterm-backend",
    "termion-backend",
]
