[package]
name = "parts_manager"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"
description = "A GPT Partition Manager"

[dependencies]
parts = { path = "../_NiteLinux/Userspace/parts" }
structopt = "0.3.12"
anyhow = "1.0.27"
linapi = { version = "0.4.4-alpha.0", path = "../linapi" }
byte-unit = "3.0.3"
serde_json = "1.0.48"
serde = { version = "1.0.105", features = ["derive"] }

[dependencies.cursive]
version = "0.14.0"
default-features = false
features = [
    # "crossterm-backend",
    "termion-backend",
]
